# -----------------------------------------------------------------------------
# TEST Configuration for the Yaqui Valley Example
# -----------------------------------------------------------------------------

data_dir: "../data"
output_dir: "../outputs"

aoi_file: "aoi_yaqui_test.gpkg"
labels_file: "crop_labels_yaqui_test.gpkg"
labels_field_name: "crop_name"

study_period:
  start_date: "2017-10-01"
  end_date: "2018-05-31"

segmentation_composite_uses_full_study_period: true
segmentation_composite_custom_range:
  start_date: ""
  end_date: ""

segmentation_params:
  num_clusters: 80
  min_n_pxls: 100
  bands: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

output_names:
  segmentation_image: "GM_Seg_Composite_Test.tif"
  segmented_clumps: "segmented_clumps_test.kea"
  segmented_polygons: "segmented_polygons_test.shp"
  labeled_polygons: "labeled_polygons_test.shp"
  rasterized_labels: "rasterized_labels_test.tif"
  features_csv: "features_test.csv"

# -----------------------------------------------------------------------------
# Modeling Parameters
# -----------------------------------------------------------------------------
modeling_params:
  test_size: 0.3
  random_state: 42
  balance_classes: true
  max_samples_per_class: 500
  tpot_generations: 5
  tpot_population_size: 20
  output_model_name: "tpot_model_test.pkl"
  output_prediction_name: "predictions_test.csv"
  output_map_name: "predicted_map_test.gpkg"

# -----------------------------------------------------------------------------
# Prediction for a New Year
# -----------------------------------------------------------------------------
prediction_year: 2019
