# -----------------------------------------------------------------------------
# General Configuration
# -----------------------------------------------------------------------------
aoi_name: "AOI_Chihuahua_2023"
data_dir: "../data"
output_dir: "../outputs"

# -----------------------------------------------------------------------------
# Data Source Configuration
# -----------------------------------------------------------------------------
aoi_file: "AOI_Chihuahua.gpkg"
labels_file: "etiquetas_chihuahua.gpkg"
labels_field_name: "klass"

# -----------------------------------------------------------------------------
# Date & Time Period Configuration
# -----------------------------------------------------------------------------
# Define the overall study period. Monthly composites will be generated
# automatically for each month within this range.
study_period:
  start_date: "2023-04-01"
  end_date: "2023-11-30"

# Configuration for the main composite image used for segmentation.
# If true, it will use the full study_period defined above.
# If false, you must specify a custom start and end date below.
segmentation_composite_uses_full_study_period: false
segmentation_composite_custom_range:
  start_date: "2023-05-01"
  end_date: "2023-11-30"

# -----------------------------------------------------------------------------
# Processing Parameters
# -----------------------------------------------------------------------------
segmentation_params:
  num_clusters: 80
  min_n_pxls: 100
  dist_thres: 100.0
  bands: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

# -----------------------------------------------------------------------------
# Output File Naming
# -----------------------------------------------------------------------------
output_names:
  segmentation_image: "GM_Seg_Composite.tif"
  segmented_clumps: "segmented_clumps.kea"
  segmented_polygons: "segmented_polygons.shp"
  labeled_polygons: "labeled_polygons.shp"
  rasterized_labels: "rasterized_labels.tif"
  features_csv: "features.csv"