name: geocrop_analysis_mx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2
  - gdal
  - geopandas
  - rasterio
  - rsgislib
  - earthengine-api
  - pandas
  - scikit-learn
  - pytorch  
  - pycaret
  - tpot
  - requests
  - pyyaml
  - mamba  
