name: geocrop_analysis_mx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - geopandas
  - rasterio
  - earthengine-api
  - pandas
  - numpy<2
  - scikit-learn
  - scikit-image
  - pycaret
  - tpot==0.12.2
  - pytorch
  - requests
  - pyyaml
  - pyshepseg
  - exactextract
